### ISSUE TITLE
发现首页底部导航切换页面的时候会有渐变的过度,能去掉渐变吗

### ISSUE THREAD

**Issue by lodgkk** [linxiangcheer/PlayAndroid#1]
发现首页底部导航切换页面的时候会有渐变的过度,能去掉渐变吗

**Comment by linxiangcheer** [comment]
这个是navigation目前默认的页面过渡动画，暂时没有去掉的打算，因为在未来，navigation2.5可以支持设置页面切换动画，其中包括共享元素动画。
如果你想提前使用，可以依赖accompanist库的navigation animation https://github.com/google/accompanist/tree/main/navigation-animation。应该是0.17.0之后的版本，就可以设置其他页面切换动画

**Comment by lodgkk** [comment]
难怪,我测试机是5.1,切换的时候很明显,还有点卡
