### ISSUE TITLE
请问报这种错误是为什么呢

### ISSUE THREAD

**Issue by zhengrongGG** [linxiangcheer/PlayAndroid#2]
你好，我这报这个错误，能指导下吗，折腾了一阵了

![image](https://user-images.githubusercontent.com/35477688/136887495-7dc16d8f-386c-4e5b-b772-6ada0e6ac4c8.png)

**Comment by linxiangcheer** [comment]
dependencies中添加添加依赖试试

> implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9")
