### ISSUE TITLE
必须赞一个

### ISSUE THREAD

**Issue by wjbd** [linxiangcheer/PlayAndroid#4]
项目很不错，让我茅塞对开啊

**Comment by linxiangcheer** [comment]
感谢肯定😸

**Comment by wjbd** [comment]
请问大佬，你做的rememberLazyState，为什么就可以保存paging3的数据和列表状态，我这边每次点击bottom切换页面，都会重新刷新一次页面，不知道怎么解决这个问题

**Comment by wjbd** [comment]
同样的，我发现了你的项目中，SquareViewModel获取的时候使用viewModel()获取的全都是同一个内存地址的viewmodel，而我的项目中，每次刷新一下页面，viewmodel都会重新生成，内存地址也发生了变化，是不是这个原因导致的不能保存状态呢？viewmodel怎么保证使用viewModel()方法生成的是同一个viewmodel呢？

**Comment by wjbd** [comment]
我在测试之后，把viewmodel提到了顶层，保证了viewmodel是同一个，但是还是没有办法保存列表状态

**Comment by linxiangcheer** [comment]
保存列表状态看这里哦
https://juejin.cn/post/7007793503971328031
