### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by Jesen0823** [linxiangcheer/PlayAndroid#5]
学习了大佬的分享，尤其是请求封装那块，我自己也写了个小东西。
请教一下，我自己写的也有下面这个问题，原想来这里参考：
每点击顶部tab或底部tab,进入加载过的页面，网络请求会重新触发加载，怎么才能在不使用数据库持久化的情况下优化paging网络请求，以节省流量

**Comment by linxiangcheer** [comment]
请求前判断有无数据，有的话return不执行网络请求的代码就好了，这是最简单的方法

**Comment by Jesen0823** [comment]
好的多谢，这样做确实是可以
